[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
# f0x01 = "2UimA9XeFtc4e16WnkwaFkhv8KSQdWr7CGEKk7hDpKea"

# [programs.devnet]
f0x01 = "5zbzYLKziAmPUMv25xHo4XWkbbAsp21q6D5EM7J9c6r6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# wallet = "./wallet.json"
wallet = "~/.config/solana/id.json"

[scripts]
# runs test in specific order.
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.ts tests/user.ts tests/commitment.ts tests/session.ts"